### ISSUE TITLE
Suggestion: support for terumet doors

### ISSUE THREAD

**Issue by Lanhild** [oversword/bigdoors#29]

**Comment by oversword** [comment]
Sorry @Lanhild this is not an issue. I'm relatively sure this does "support" terumet doors. What it DOESN'T do is override them by default, which I do not believe it should.

If you would like this feature on the server, you can request that terumet doors be registered as bigdoors in bls_custom or the issue_tracker, we will need to consider each set of doors we add to the server since we are approaching the node limit and this mod registers 36 new nodes for each door we add.

I will quickly double check that it does in fact support terumet doors and not break...

**Comment by oversword** [comment]
I can confirm this already works with terumet doors & they look awesome
