### ISSUE TITLE
Serialization of door size

### ISSUE THREAD

**Issue by fluxionary** [oversword/bigdoors#3]
You should always put some sort of delimiter (like a space or a comma) between separate values. It may not matter because you probably will never have a 10x1 door, but it's a good practice.

https://github.com/oversword/bigdoors/blob/9ad025d93b92004c5c5f8d97206b9407eb242ebf/register.lua#L23

Also, is `string_to_size` supposed to be the inverse of `size_to_string? Why does it divide by 10?

**Comment by oversword** [comment]
I think you answered your own question with another question.
The size_string does not require a delimiter because the values are multiplied by 10, and so the values are always 2-length strings. `size_to_string` and `string_to_size` are direct inverses, see `numstr` which multiplies by 10, floors, and maintains 2-length. This has the restriction that sizes can come in increments of 1/10 at the smallest - but, I mean - deal with it. I only intended it to go down to 1/2 anyways.

The one valid takaway from this issue is that I need to restrict the possible sizes to make sure no one tries to add in something >= 10 wide/high.

**Comment by oversword** [comment]
https://github.com/oversword/bigdoors/pull/13/files?diff=unified&w=1

**Comment by fluxionary** [comment]
That works :)
