### ISSUE TITLE
Differentiate the icons

### ISSUE THREAD

**Issue by fluxionary** [oversword/bigdoors#6]
I don't know what the "correct" solution for this is, but it's a problem that the icons for all the sizes look identical rn. 

Some ideas:
* Use https://github.com/minetest/minetest/blob/40ad9767531beb6cf2e8bd918c9c9ed5f2749320/doc/lua_api.txt#L482 to scale the inventory image
* Use https://github.com/minetest/minetest/blob/40ad9767531beb6cf2e8bd918c9c9ed5f2749320/doc/lua_api.txt#L412 to overlay some text showing the size over the default (you'll have to make the overlay textures)

**Comment by oversword** [comment]
It's way harder than it should be to make overlay textures that are readable and look good, I think I'll try tomorrow on a canvas so I can do it dynamically because GIMP is awful at text editing

**Comment by fluxionary** [comment]
https://opengameart.org/content/minimalist-pixel-fonts

i wouldn't even bother installing the font. just draw some #s in a few pixels

**Comment by oversword** [comment]
I'm not sure that will work, scaling can mess up the pixels and I would still need to do a background color so it's readable over any other icon

**Comment by fluxionary** [comment]
i'll try to make a PR tomorrow

**Comment by oversword** [comment]
Hm okay, I'm calling it a night too, thanks for the help!

**Comment by oversword** [comment]
@fluxionary can you checkout
https://github.com/oversword/bigdoors/tree/issue-6-large
and
https://github.com/oversword/bigdoors/tree/issue-6-small


I think I'd prefer the small ones because they don't obstruct the original too much, but I worry they're too small to be visible so I have also tried out a larger variant.

Let me know which you prefer, I could try and find a middleground too if you don't like either, also happy to take a look at any PR you want to offer.

**Comment by oversword** [comment]
I tried a medium one too
https://github.com/oversword/bigdoors/tree/issue-6-medium
It's probably better
